export const movieList = [
    {
        id: 1,
        title: "Star Wars",
        genre: "Sci-Fi",
        age: "Pg",
        image: src/Images/Movie-Posters/images/star-wars.webp,
        rating: "5 stars",
    },
    {
        id: 2,
        title: "300",
        genre: "Action",
        age: "R16",
        image: ,
        rating: "3 stars",
    },
    {
        id: 3,
        title: "Straight outta Compton",
        genre: "Drama",
        age: "R16",
        image: src/Images/Movie-Posters/images/straight-outta-compton.webp,
        rating: "4 stars",
    },
    {
        id: 4,
        title: "Black Dynamite",
        genre: "Comedy",
        age: "R16",
        image: ,
        rating: "5 stars",
    },
    {
        id: 5,
        title: "Snake in the Eagle's shadow",
        genre: "Action",
        age: "M",
        image: ,
        rating: "5 stars",
    },
    {
        id: 6,
        title: "Ip Man",
        genre: "Action",
        age: "R16",
        image: ,
        rating: "5 stars",
    },
    {
        id: 7,
        title: "Enter the Dragon",
        genre: "Action",
        age: "R16",
        image: src/Images/Movie-Posters/images/enter-the-dragon.webp,
        rating: "5 stars",
    },
    {
        id: 8,
        title: "The Simpsons Movie",
        genre: "Comedy",
        age: "Pg",
        image: src/Images/Movie-Posters/images/the-simpsons-movie.webp,
        rating: "5 stars",
    },
    {
        id: 9,
        title: "Drunken Master",
        genre: "Comedy",
        age: "Pg",
        image: ,
        rating: "3 stars",
    },
    {
        id: 10,
        title: "Saving Private Ryan",
        genre: "Action",
        age: "R15",
        image: src/Images/Movie-Posters/images/saving-private-ryan.jpg,
        rating: "5 stars",
    },
    {
        id: 11,
        title: "Killing Machine (Shorinji Kempo)",
        genre: "Action",
        age: "M",
        image: ,
        rating: "5 stars",
    },
    {
        id: 12,
        title: "American Pie",
        genre: "Comedy",
        age: "R16",
        image: src/Images/Movie-Posters/images/american-pie.webp,
        rating: "2 stars",
    },
    {
        id: 13,
        title: "Kung-Fu Hustle",
        genre: "Comedy",
        age: "Pg",
        image: ,
        rating: "4 stars",
    },
    {
        id: 14,
        title: "The Notebook",
        genre: "Romance",
        age: "Pg",
        image: ,
        rating: "3 stars",
    },
    {
        id: 15,
        title: "I love you man",
        genre: "Comedy",
        age: "R16",
        image: ,
        rating: "5 stars",
    },
    {
        id: 16,
        title: "Alien",
        genre: "Horror",
        age: "R16",
        image: ,
        rating: "5 stars",
    },
    {
        id: 17,
        title: "A Nightmare on Elm St",
        genre: "Horror",
        age: "R16",
        image: ,
        rating: "4 stars",
    },
    {
        id: 18,
        title: "The Last Samurai",
        genre: "Action",
        age: "M",
        image: ,
        rating: "5 stars",
    },
    {
        id: 19,
        title: "My Sassy Girl",
        genre: "Comedy",
        age: "Pg",
        image: ,
        rating: "5 stars",
    },
    {
        id: 20,
        title: "From Up on Poppy Hill",
        genre: "Animation",
        age: "Pg",
        image: ,
        rating: "5 stars",
    },
    {
        id: 20,
        title: "Spirited Away",
        genre: "Animation",
        age: "Pg",
        image: ,
        rating: "5 stars",
    },
]