export const movieList = [
    {
        id: 1,
        title: "Star Wars",
        genre: "Sci-Fi",
        image: ,
        rating: ,
    },
    {
        id: 2,
        title: "300",
        genre: "Action",
        image: ,
        rating: ,
    },
    {
        id: 3,
        title: "Straight outta Compton",
        genre: "Drama",
        image: ,
        rating: ,
    },
    {
        id: 4,
        title: "Black Dynamite",
        genre: "Comedy",
        image: ,
        rating: ,
    },
    {
        id: 5,
        title: "Snake in the Eagle's shadow",
        genre: "Action",
        image: ,
        rating: ,
    },
    {
        id: 6,
        title: "Ip Man",
        genre: "Action",
        image: ,
        rating: ,
    },
    {
        id: 7,
        title: "Enter the Dragon",
        genre: "Action",
        image: ,
        rating: ,
    },
    {
        id: 8,
        title: "The Simpsons Movie",
        genre: "Comedy",
        image: ,
        rating: ,
    },
    {
        id: 9,
        title: "Drunken Master",
        genre: "Comedy",
        image: ,
        rating: ,
    },
    {
        id: 10,
        title: "Saving Private Ryan",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 11,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 12,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 13,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 14,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 15,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 16,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 17,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 18,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 19,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
    {
        id: 20,
        title: "",
        genre: "",
        image: ,
        rating: ,
    },
]